SELECT DISTINCT(D.ID), D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES AS SC INNER JOIN DEVELOPERS AS D ON SC.CATEGORY = 'FRONT END' AND D.SKILL_CODE & SC.CODE > 0
ORDER BY D.ID ASC

---------------------------------------------------------------------------------

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES SC
JOIN DEVELOPERS D ON SC.CATEGORY = 'Front End' AND BITAND(D.SKILL_CODE, SC.CODE) > 0
ORDER BY D.ID ASC;