WITH RECURSIVE GENERATIONS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN GENERATIONS G ON E.PARENT_ID = G.ID
)

SELECT COUNT(G.ID) AS COUNT, G.GENERATION
FROM GENERATIONS G
WHERE NOT EXISTS (SELECT 1 
                  FROM ECOLI_DATA E2 
                  WHERE E2.PARENT_ID = G.ID)
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC;


------------------------------------------

SELECT LEVEL AS GENERATION, COUNT(ID) AS COUNT
FROM ECOLI_DATA
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID 
                 FROM ECOLI_DATA 
                 WHERE PARENT_ID IS NOT NULL)
START WITH PARENT_ID IS NULL
CONNECT BY PRIOR ID = PARENT_ID
GROUP BY LEVEL
ORDER BY LEVEL;